// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.cotx.example.helloworld;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
