// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ovsdb/ovs/core/OvsBridge.proto

package com.cotx.ovsctl.message.ovsdb.ovs.core;

import com.cotx.ovsctl.message.common.ControlProtocolVersion;
import com.cotx.ovsctl.message.common.ControllerInfo;
import com.cotx.ovsctl.message.common.ControllerInfoOrBuilder;
import com.cotx.ovsctl.message.description.BridgeDescription;

/**
 * <pre>
 *1. define OvsBridge message type.
 *2. AddBridgeRequest's message item.
 * </pre>
 *
 * Protobuf type {@code OvsBridge}
 */
public  final class OvsBridge extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OvsBridge)
    OvsBridgeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OvsBridge.newBuilder() to construct.
  private OvsBridge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OvsBridge() {
    uuid_ = "";
    name_ = "";
    failMode_ = 0;
    controllers_ = java.util.Collections.emptyList();
    datapathType_ = "";
    controlProtocols_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OvsBridge(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            failMode_ = rawValue;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              controllers_ = new java.util.ArrayList<ControllerInfo>();
              mutable_bitField0_ |= 0x00000008;
            }
            controllers_.add(
                input.readMessage(ControllerInfo.PARSER, extensionRegistry));
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            datapathType_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              controlProtocols_ = new java.util.ArrayList<Integer>();
              mutable_bitField0_ |= 0x00000020;
            }
            controlProtocols_.add(rawValue);
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                controlProtocols_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              controlProtocols_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              otherConfigs_ = com.google.protobuf.MapField.newMapField(
                  OtherConfigsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000040;
            }
            com.google.protobuf.MapEntry<String, String>
            otherConfigs__ = input.readMessage(
                OtherConfigsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            otherConfigs_.getMutableMap().put(
                otherConfigs__.getKey(), otherConfigs__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        controllers_ = java.util.Collections.unmodifiableList(controllers_);
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        controlProtocols_ = java.util.Collections.unmodifiableList(controlProtocols_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return OvsBridgeProto.internal_static_OvsBridge_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 7:
        return internalGetOtherConfigs();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return OvsBridgeProto.internal_static_OvsBridge_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            OvsBridge.class, Builder.class);
  }

  private int bitField0_;
  public static final int UUID_FIELD_NUMBER = 1;
  private volatile Object uuid_;
  /**
   * <code>string uuid = 1;</code>
   */
  public String getUuid() {
    Object ref = uuid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUuidBytes() {
    Object ref = uuid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAILMODE_FIELD_NUMBER = 3;
  private int failMode_;
  /**
   * <pre>
   * OpenFlow properties 
   * </pre>
   *
   * <code>.BridgeDescription.FailMode failMode = 3;</code>
   */
  public int getFailModeValue() {
    return failMode_;
  }
  /**
   * <pre>
   * OpenFlow properties 
   * </pre>
   *
   * <code>.BridgeDescription.FailMode failMode = 3;</code>
   */
  public BridgeDescription.FailMode getFailMode() {
    BridgeDescription.FailMode result = BridgeDescription.FailMode.valueOf(failMode_);
    return result == null ? BridgeDescription.FailMode.UNRECOGNIZED : result;
  }

  public static final int CONTROLLERS_FIELD_NUMBER = 4;
  private java.util.List<ControllerInfo> controllers_;
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControllerInfo controllers = 4;</code>
   */
  public java.util.List<ControllerInfo> getControllersList() {
    return controllers_;
  }
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControllerInfo controllers = 4;</code>
   */
  public java.util.List<? extends ControllerInfoOrBuilder>
      getControllersOrBuilderList() {
    return controllers_;
  }
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControllerInfo controllers = 4;</code>
   */
  public int getControllersCount() {
    return controllers_.size();
  }
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControllerInfo controllers = 4;</code>
   */
  public ControllerInfo getControllers(int index) {
    return controllers_.get(index);
  }
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControllerInfo controllers = 4;</code>
   */
  public ControllerInfoOrBuilder getControllersOrBuilder(
      int index) {
    return controllers_.get(index);
  }

  public static final int DATAPATHTYPE_FIELD_NUMBER = 5;
  private volatile Object datapathType_;
  /**
   * <pre>
   * Adds more properties 
   * </pre>
   *
   * <code>string datapathType = 5;</code>
   */
  public String getDatapathType() {
    Object ref = datapathType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      datapathType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Adds more properties 
   * </pre>
   *
   * <code>string datapathType = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDatapathTypeBytes() {
    Object ref = datapathType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      datapathType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTROLPROTOCOLS_FIELD_NUMBER = 6;
  private java.util.List<Integer> controlProtocols_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      Integer, ControlProtocolVersion> controlProtocols_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              Integer, ControlProtocolVersion>() {
            public ControlProtocolVersion convert(Integer from) {
              ControlProtocolVersion result = ControlProtocolVersion.valueOf(from);
              return result == null ? ControlProtocolVersion.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
   */
  public java.util.List<ControlProtocolVersion> getControlProtocolsList() {
    return new com.google.protobuf.Internal.ListAdapter<
        Integer, ControlProtocolVersion>(controlProtocols_, controlProtocols_converter_);
  }
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
   */
  public int getControlProtocolsCount() {
    return controlProtocols_.size();
  }
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
   */
  public ControlProtocolVersion getControlProtocols(int index) {
    return controlProtocols_converter_.convert(controlProtocols_.get(index));
  }
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
   */
  public java.util.List<Integer>
  getControlProtocolsValueList() {
    return controlProtocols_;
  }
  /**
   * <pre>
   * Add control protocol version property 
   * </pre>
   *
   * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
   */
  public int getControlProtocolsValue(int index) {
    return controlProtocols_.get(index);
  }
  private int controlProtocolsMemoizedSerializedSize;

  public static final int OTHERCONFIGS_FIELD_NUMBER = 7;
  private static final class OtherConfigsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                OvsBridgeProto.internal_static_OvsBridge_OtherConfigsEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> otherConfigs_;
  private com.google.protobuf.MapField<String, String>
  internalGetOtherConfigs() {
    if (otherConfigs_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          OtherConfigsDefaultEntryHolder.defaultEntry);
    }
    return otherConfigs_;
  }

  public int getOtherConfigsCount() {
    return internalGetOtherConfigs().getMap().size();
  }
  /**
   * <pre>
   * other optional configs 
   * </pre>
   *
   * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
   */

  public boolean containsOtherConfigs(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetOtherConfigs().getMap().containsKey(key);
  }
  /**
   * Use {@link #getOtherConfigsMap()} instead.
   */
  @Deprecated
  public java.util.Map<String, String> getOtherConfigs() {
    return getOtherConfigsMap();
  }
  /**
   * <pre>
   * other optional configs 
   * </pre>
   *
   * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
   */

  public java.util.Map<String, String> getOtherConfigsMap() {
    return internalGetOtherConfigs().getMap();
  }
  /**
   * <pre>
   * other optional configs 
   * </pre>
   *
   * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
   */

  public String getOtherConfigsOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetOtherConfigs().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * other optional configs 
   * </pre>
   *
   * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
   */

  public String getOtherConfigsOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetOtherConfigs().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getControllersCount(); i++) {
      if (!getControllers(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (failMode_ != BridgeDescription.FailMode.SECURE.getNumber()) {
      output.writeEnum(3, failMode_);
    }
    for (int i = 0; i < controllers_.size(); i++) {
      output.writeMessage(4, controllers_.get(i));
    }
    if (!getDatapathTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, datapathType_);
    }
    if (getControlProtocolsList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(controlProtocolsMemoizedSerializedSize);
    }
    for (int i = 0; i < controlProtocols_.size(); i++) {
      output.writeEnumNoTag(controlProtocols_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetOtherConfigs(),
        OtherConfigsDefaultEntryHolder.defaultEntry,
        7);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (failMode_ != BridgeDescription.FailMode.SECURE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, failMode_);
    }
    for (int i = 0; i < controllers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, controllers_.get(i));
    }
    if (!getDatapathTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, datapathType_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < controlProtocols_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(controlProtocols_.get(i));
      }
      size += dataSize;
      if (!getControlProtocolsList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }controlProtocolsMemoizedSerializedSize = dataSize;
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetOtherConfigs().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      otherConfigs__ = OtherConfigsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, otherConfigs__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof OvsBridge)) {
      return super.equals(obj);
    }
    OvsBridge other = (OvsBridge) obj;

    boolean result = true;
    result = result && getUuid()
        .equals(other.getUuid());
    result = result && getName()
        .equals(other.getName());
    result = result && failMode_ == other.failMode_;
    result = result && getControllersList()
        .equals(other.getControllersList());
    result = result && getDatapathType()
        .equals(other.getDatapathType());
    result = result && controlProtocols_.equals(other.controlProtocols_);
    result = result && internalGetOtherConfigs().equals(
        other.internalGetOtherConfigs());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + FAILMODE_FIELD_NUMBER;
    hash = (53 * hash) + failMode_;
    if (getControllersCount() > 0) {
      hash = (37 * hash) + CONTROLLERS_FIELD_NUMBER;
      hash = (53 * hash) + getControllersList().hashCode();
    }
    hash = (37 * hash) + DATAPATHTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDatapathType().hashCode();
    if (getControlProtocolsCount() > 0) {
      hash = (37 * hash) + CONTROLPROTOCOLS_FIELD_NUMBER;
      hash = (53 * hash) + controlProtocols_.hashCode();
    }
    if (!internalGetOtherConfigs().getMap().isEmpty()) {
      hash = (37 * hash) + OTHERCONFIGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetOtherConfigs().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static OvsBridge parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static OvsBridge parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static OvsBridge parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static OvsBridge parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static OvsBridge parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static OvsBridge parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static OvsBridge parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static OvsBridge parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static OvsBridge parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static OvsBridge parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static OvsBridge parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static OvsBridge parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(OvsBridge prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *1. define OvsBridge message type.
   *2. AddBridgeRequest's message item.
   * </pre>
   *
   * Protobuf type {@code OvsBridge}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OvsBridge)
      OvsBridgeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OvsBridgeProto.internal_static_OvsBridge_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetOtherConfigs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableOtherConfigs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OvsBridgeProto.internal_static_OvsBridge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OvsBridge.class, Builder.class);
    }

    // Construct using OvsBridge.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getControllersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      uuid_ = "";

      name_ = "";

      failMode_ = 0;

      if (controllersBuilder_ == null) {
        controllers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        controllersBuilder_.clear();
      }
      datapathType_ = "";

      controlProtocols_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableOtherConfigs().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return OvsBridgeProto.internal_static_OvsBridge_descriptor;
    }

    public OvsBridge getDefaultInstanceForType() {
      return OvsBridge.getDefaultInstance();
    }

    public OvsBridge build() {
      OvsBridge result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public OvsBridge buildPartial() {
      OvsBridge result = new OvsBridge(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.uuid_ = uuid_;
      result.name_ = name_;
      result.failMode_ = failMode_;
      if (controllersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          controllers_ = java.util.Collections.unmodifiableList(controllers_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.controllers_ = controllers_;
      } else {
        result.controllers_ = controllersBuilder_.build();
      }
      result.datapathType_ = datapathType_;
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        controlProtocols_ = java.util.Collections.unmodifiableList(controlProtocols_);
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.controlProtocols_ = controlProtocols_;
      result.otherConfigs_ = internalGetOtherConfigs();
      result.otherConfigs_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof OvsBridge) {
        return mergeFrom((OvsBridge)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(OvsBridge other) {
      if (other == OvsBridge.getDefaultInstance()) return this;
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.failMode_ != 0) {
        setFailModeValue(other.getFailModeValue());
      }
      if (controllersBuilder_ == null) {
        if (!other.controllers_.isEmpty()) {
          if (controllers_.isEmpty()) {
            controllers_ = other.controllers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureControllersIsMutable();
            controllers_.addAll(other.controllers_);
          }
          onChanged();
        }
      } else {
        if (!other.controllers_.isEmpty()) {
          if (controllersBuilder_.isEmpty()) {
            controllersBuilder_.dispose();
            controllersBuilder_ = null;
            controllers_ = other.controllers_;
            bitField0_ = (bitField0_ & ~0x00000008);
            controllersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getControllersFieldBuilder() : null;
          } else {
            controllersBuilder_.addAllMessages(other.controllers_);
          }
        }
      }
      if (!other.getDatapathType().isEmpty()) {
        datapathType_ = other.datapathType_;
        onChanged();
      }
      if (!other.controlProtocols_.isEmpty()) {
        if (controlProtocols_.isEmpty()) {
          controlProtocols_ = other.controlProtocols_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureControlProtocolsIsMutable();
          controlProtocols_.addAll(other.controlProtocols_);
        }
        onChanged();
      }
      internalGetMutableOtherConfigs().mergeFrom(
          other.internalGetOtherConfigs());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getControllersCount(); i++) {
        if (!getControllers(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      OvsBridge parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (OvsBridge) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     */
    public String getUuid() {
      Object ref = uuid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public Builder setUuid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int failMode_ = 0;
    /**
     * <pre>
     * OpenFlow properties 
     * </pre>
     *
     * <code>.BridgeDescription.FailMode failMode = 3;</code>
     */
    public int getFailModeValue() {
      return failMode_;
    }
    /**
     * <pre>
     * OpenFlow properties 
     * </pre>
     *
     * <code>.BridgeDescription.FailMode failMode = 3;</code>
     */
    public Builder setFailModeValue(int value) {
      failMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OpenFlow properties 
     * </pre>
     *
     * <code>.BridgeDescription.FailMode failMode = 3;</code>
     */
    public BridgeDescription.FailMode getFailMode() {
      BridgeDescription.FailMode result = BridgeDescription.FailMode.valueOf(failMode_);
      return result == null ? BridgeDescription.FailMode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * OpenFlow properties 
     * </pre>
     *
     * <code>.BridgeDescription.FailMode failMode = 3;</code>
     */
    public Builder setFailMode(BridgeDescription.FailMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      failMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OpenFlow properties 
     * </pre>
     *
     * <code>.BridgeDescription.FailMode failMode = 3;</code>
     */
    public Builder clearFailMode() {
      
      failMode_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<ControllerInfo> controllers_ =
      java.util.Collections.emptyList();
    private void ensureControllersIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        controllers_ = new java.util.ArrayList<ControllerInfo>(controllers_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            ControllerInfo, ControllerInfo.Builder, ControllerInfoOrBuilder> controllersBuilder_;

    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public java.util.List<ControllerInfo> getControllersList() {
      if (controllersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(controllers_);
      } else {
        return controllersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public int getControllersCount() {
      if (controllersBuilder_ == null) {
        return controllers_.size();
      } else {
        return controllersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public ControllerInfo getControllers(int index) {
      if (controllersBuilder_ == null) {
        return controllers_.get(index);
      } else {
        return controllersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder setControllers(
        int index, ControllerInfo value) {
      if (controllersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureControllersIsMutable();
        controllers_.set(index, value);
        onChanged();
      } else {
        controllersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder setControllers(
        int index, ControllerInfo.Builder builderForValue) {
      if (controllersBuilder_ == null) {
        ensureControllersIsMutable();
        controllers_.set(index, builderForValue.build());
        onChanged();
      } else {
        controllersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder addControllers(ControllerInfo value) {
      if (controllersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureControllersIsMutable();
        controllers_.add(value);
        onChanged();
      } else {
        controllersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder addControllers(
        int index, ControllerInfo value) {
      if (controllersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureControllersIsMutable();
        controllers_.add(index, value);
        onChanged();
      } else {
        controllersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder addControllers(
        ControllerInfo.Builder builderForValue) {
      if (controllersBuilder_ == null) {
        ensureControllersIsMutable();
        controllers_.add(builderForValue.build());
        onChanged();
      } else {
        controllersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder addControllers(
        int index, ControllerInfo.Builder builderForValue) {
      if (controllersBuilder_ == null) {
        ensureControllersIsMutable();
        controllers_.add(index, builderForValue.build());
        onChanged();
      } else {
        controllersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder addAllControllers(
        Iterable<? extends ControllerInfo> values) {
      if (controllersBuilder_ == null) {
        ensureControllersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, controllers_);
        onChanged();
      } else {
        controllersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder clearControllers() {
      if (controllersBuilder_ == null) {
        controllers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        controllersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public Builder removeControllers(int index) {
      if (controllersBuilder_ == null) {
        ensureControllersIsMutable();
        controllers_.remove(index);
        onChanged();
      } else {
        controllersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public ControllerInfo.Builder getControllersBuilder(
        int index) {
      return getControllersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public ControllerInfoOrBuilder getControllersOrBuilder(
        int index) {
      if (controllersBuilder_ == null) {
        return controllers_.get(index);  } else {
        return controllersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public java.util.List<? extends ControllerInfoOrBuilder>
         getControllersOrBuilderList() {
      if (controllersBuilder_ != null) {
        return controllersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(controllers_);
      }
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public ControllerInfo.Builder addControllersBuilder() {
      return getControllersFieldBuilder().addBuilder(
          ControllerInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public ControllerInfo.Builder addControllersBuilder(
        int index) {
      return getControllersFieldBuilder().addBuilder(
          index, ControllerInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControllerInfo controllers = 4;</code>
     */
    public java.util.List<ControllerInfo.Builder>
         getControllersBuilderList() {
      return getControllersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            ControllerInfo, ControllerInfo.Builder, ControllerInfoOrBuilder>
        getControllersFieldBuilder() {
      if (controllersBuilder_ == null) {
        controllersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                ControllerInfo, ControllerInfo.Builder, ControllerInfoOrBuilder>(
                controllers_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        controllers_ = null;
      }
      return controllersBuilder_;
    }

    private Object datapathType_ = "";
    /**
     * <pre>
     * Adds more properties 
     * </pre>
     *
     * <code>string datapathType = 5;</code>
     */
    public String getDatapathType() {
      Object ref = datapathType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        datapathType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Adds more properties 
     * </pre>
     *
     * <code>string datapathType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDatapathTypeBytes() {
      Object ref = datapathType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        datapathType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Adds more properties 
     * </pre>
     *
     * <code>string datapathType = 5;</code>
     */
    public Builder setDatapathType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datapathType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Adds more properties 
     * </pre>
     *
     * <code>string datapathType = 5;</code>
     */
    public Builder clearDatapathType() {
      
      datapathType_ = getDefaultInstance().getDatapathType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Adds more properties 
     * </pre>
     *
     * <code>string datapathType = 5;</code>
     */
    public Builder setDatapathTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datapathType_ = value;
      onChanged();
      return this;
    }

    private java.util.List<Integer> controlProtocols_ =
      java.util.Collections.emptyList();
    private void ensureControlProtocolsIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        controlProtocols_ = new java.util.ArrayList<Integer>(controlProtocols_);
        bitField0_ |= 0x00000020;
      }
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public java.util.List<ControlProtocolVersion> getControlProtocolsList() {
      return new com.google.protobuf.Internal.ListAdapter<
          Integer, ControlProtocolVersion>(controlProtocols_, controlProtocols_converter_);
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public int getControlProtocolsCount() {
      return controlProtocols_.size();
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public ControlProtocolVersion getControlProtocols(int index) {
      return controlProtocols_converter_.convert(controlProtocols_.get(index));
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public Builder setControlProtocols(
        int index, ControlProtocolVersion value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureControlProtocolsIsMutable();
      controlProtocols_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public Builder addControlProtocols(ControlProtocolVersion value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureControlProtocolsIsMutable();
      controlProtocols_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public Builder addAllControlProtocols(
        Iterable<? extends ControlProtocolVersion> values) {
      ensureControlProtocolsIsMutable();
      for (ControlProtocolVersion value : values) {
        controlProtocols_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public Builder clearControlProtocols() {
      controlProtocols_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public java.util.List<Integer>
    getControlProtocolsValueList() {
      return java.util.Collections.unmodifiableList(controlProtocols_);
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public int getControlProtocolsValue(int index) {
      return controlProtocols_.get(index);
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public Builder setControlProtocolsValue(
        int index, int value) {
      ensureControlProtocolsIsMutable();
      controlProtocols_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public Builder addControlProtocolsValue(int value) {
      ensureControlProtocolsIsMutable();
      controlProtocols_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Add control protocol version property 
     * </pre>
     *
     * <code>repeated .ControlProtocolVersion controlProtocols = 6;</code>
     */
    public Builder addAllControlProtocolsValue(
        Iterable<Integer> values) {
      ensureControlProtocolsIsMutable();
      for (int value : values) {
        controlProtocols_.add(value);
      }
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> otherConfigs_;
    private com.google.protobuf.MapField<String, String>
    internalGetOtherConfigs() {
      if (otherConfigs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OtherConfigsDefaultEntryHolder.defaultEntry);
      }
      return otherConfigs_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableOtherConfigs() {
      onChanged();;
      if (otherConfigs_ == null) {
        otherConfigs_ = com.google.protobuf.MapField.newMapField(
            OtherConfigsDefaultEntryHolder.defaultEntry);
      }
      if (!otherConfigs_.isMutable()) {
        otherConfigs_ = otherConfigs_.copy();
      }
      return otherConfigs_;
    }

    public int getOtherConfigsCount() {
      return internalGetOtherConfigs().getMap().size();
    }
    /**
     * <pre>
     * other optional configs 
     * </pre>
     *
     * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
     */

    public boolean containsOtherConfigs(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetOtherConfigs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOtherConfigsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getOtherConfigs() {
      return getOtherConfigsMap();
    }
    /**
     * <pre>
     * other optional configs 
     * </pre>
     *
     * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
     */

    public java.util.Map<String, String> getOtherConfigsMap() {
      return internalGetOtherConfigs().getMap();
    }
    /**
     * <pre>
     * other optional configs 
     * </pre>
     *
     * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
     */

    public String getOtherConfigsOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetOtherConfigs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * other optional configs 
     * </pre>
     *
     * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
     */

    public String getOtherConfigsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetOtherConfigs().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearOtherConfigs() {
      internalGetMutableOtherConfigs().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * other optional configs 
     * </pre>
     *
     * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
     */

    public Builder removeOtherConfigs(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableOtherConfigs().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableOtherConfigs() {
      return internalGetMutableOtherConfigs().getMutableMap();
    }
    /**
     * <pre>
     * other optional configs 
     * </pre>
     *
     * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
     */
    public Builder putOtherConfigs(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableOtherConfigs().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * other optional configs 
     * </pre>
     *
     * <code>map&lt;string, string&gt; otherConfigs = 7;</code>
     */

    public Builder putAllOtherConfigs(
        java.util.Map<String, String> values) {
      internalGetMutableOtherConfigs().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OvsBridge)
  }

  // @@protoc_insertion_point(class_scope:OvsBridge)
  private static final OvsBridge DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new OvsBridge();
  }

  public static OvsBridge getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OvsBridge>
      PARSER = new com.google.protobuf.AbstractParser<OvsBridge>() {
    public OvsBridge parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OvsBridge(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OvsBridge> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<OvsBridge> getParserForType() {
    return PARSER;
  }

  public OvsBridge getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

