// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ovsdb/ovs/core/OvsInterface.proto

package com.cotx.ovsctl.message.ovsdb.ovs.core;

import com.cotx.ovsctl.message.base.MapEntry;
import com.cotx.ovsctl.message.base.MapEntryOrBuilder;

public interface OvsInterfaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OvsInterface)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   */
  String getUuid();
  /**
   * <code>string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Type type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>.Type type = 3;</code>
   */
  Type getType();

  /**
   * <code>int64 mtu = 4;</code>
   */
  long getMtu();

  /**
   * <code>.MapEntry options = 5;</code>
   */
  boolean hasOptions();
  /**
   * <code>.MapEntry options = 5;</code>
   */
  MapEntry getOptions();
  /**
   * <code>.MapEntry options = 5;</code>
   */
  MapEntryOrBuilder getOptionsOrBuilder();

  /**
   * <code>int32 ofport = 6;</code>
   */
  int getOfport();
}
