// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.cotx.ovsctl.message.service;

public interface SomeLeafOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SomeLeaf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .SomeVal&gt; values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>map&lt;string, .SomeVal&gt; values = 1;</code>
   */
  boolean containsValues(
          String key);
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, SomeVal>
  getValues();
  /**
   * <code>map&lt;string, .SomeVal&gt; values = 1;</code>
   */
  java.util.Map<String, SomeVal>
  getValuesMap();
  /**
   * <code>map&lt;string, .SomeVal&gt; values = 1;</code>
   */

  SomeVal getValuesOrDefault(
          String key,
          SomeVal defaultValue);
  /**
   * <code>map&lt;string, .SomeVal&gt; values = 1;</code>
   */

  SomeVal getValuesOrThrow(
          String key);
}
