// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.cotx.ovsctl.message.service;

public interface SomeValOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SomeVal)
    com.google.protobuf.MessageOrBuilder {
}
