// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_message.proto

package com.cotx.ovsctl.message.base;

/**
 * <pre>
 * return map for rpc 
 * </pre>
 *
 * Protobuf type {@code MapEntry}
 */
public  final class MapEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MapEntry)
    MapEntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MapEntry.newBuilder() to construct.
  private MapEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MapEntry() {
    mkey_ = "";
    mvalue_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MapEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            mkey_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            mvalue_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CommonMessageProto.internal_static_MapEntry_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CommonMessageProto.internal_static_MapEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MapEntry.class, Builder.class);
  }

  public static final int MKEY_FIELD_NUMBER = 1;
  private volatile Object mkey_;
  /**
   * <code>string mkey = 1;</code>
   */
  public String getMkey() {
    Object ref = mkey_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      mkey_ = s;
      return s;
    }
  }
  /**
   * <code>string mkey = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMkeyBytes() {
    Object ref = mkey_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      mkey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MVALUE_FIELD_NUMBER = 2;
  private volatile Object mvalue_;
  /**
   * <code>string mvalue = 2;</code>
   */
  public String getMvalue() {
    Object ref = mvalue_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      mvalue_ = s;
      return s;
    }
  }
  /**
   * <code>string mvalue = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMvalueBytes() {
    Object ref = mvalue_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      mvalue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMkeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mkey_);
    }
    if (!getMvalueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mvalue_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMkeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mkey_);
    }
    if (!getMvalueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mvalue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MapEntry)) {
      return super.equals(obj);
    }
    MapEntry other = (MapEntry) obj;

    boolean result = true;
    result = result && getMkey()
        .equals(other.getMkey());
    result = result && getMvalue()
        .equals(other.getMvalue());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MKEY_FIELD_NUMBER;
    hash = (53 * hash) + getMkey().hashCode();
    hash = (37 * hash) + MVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getMvalue().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MapEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MapEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MapEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MapEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MapEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MapEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MapEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MapEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MapEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MapEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MapEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MapEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MapEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * return map for rpc 
   * </pre>
   *
   * Protobuf type {@code MapEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MapEntry)
      MapEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonMessageProto.internal_static_MapEntry_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonMessageProto.internal_static_MapEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MapEntry.class, Builder.class);
    }

    // Construct using MapEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      mkey_ = "";

      mvalue_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CommonMessageProto.internal_static_MapEntry_descriptor;
    }

    public MapEntry getDefaultInstanceForType() {
      return MapEntry.getDefaultInstance();
    }

    public MapEntry build() {
      MapEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public MapEntry buildPartial() {
      MapEntry result = new MapEntry(this);
      result.mkey_ = mkey_;
      result.mvalue_ = mvalue_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MapEntry) {
        return mergeFrom((MapEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MapEntry other) {
      if (other == MapEntry.getDefaultInstance()) return this;
      if (!other.getMkey().isEmpty()) {
        mkey_ = other.mkey_;
        onChanged();
      }
      if (!other.getMvalue().isEmpty()) {
        mvalue_ = other.mvalue_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MapEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MapEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object mkey_ = "";
    /**
     * <code>string mkey = 1;</code>
     */
    public String getMkey() {
      Object ref = mkey_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mkey_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string mkey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMkeyBytes() {
      Object ref = mkey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mkey = 1;</code>
     */
    public Builder setMkey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mkey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mkey = 1;</code>
     */
    public Builder clearMkey() {
      
      mkey_ = getDefaultInstance().getMkey();
      onChanged();
      return this;
    }
    /**
     * <code>string mkey = 1;</code>
     */
    public Builder setMkeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mkey_ = value;
      onChanged();
      return this;
    }

    private Object mvalue_ = "";
    /**
     * <code>string mvalue = 2;</code>
     */
    public String getMvalue() {
      Object ref = mvalue_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mvalue_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string mvalue = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMvalueBytes() {
      Object ref = mvalue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mvalue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mvalue = 2;</code>
     */
    public Builder setMvalue(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mvalue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mvalue = 2;</code>
     */
    public Builder clearMvalue() {
      
      mvalue_ = getDefaultInstance().getMvalue();
      onChanged();
      return this;
    }
    /**
     * <code>string mvalue = 2;</code>
     */
    public Builder setMvalueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mvalue_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MapEntry)
  }

  // @@protoc_insertion_point(class_scope:MapEntry)
  private static final MapEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MapEntry();
  }

  public static MapEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MapEntry>
      PARSER = new com.google.protobuf.AbstractParser<MapEntry>() {
    public MapEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MapEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MapEntry> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MapEntry> getParserForType() {
    return PARSER;
  }

  public MapEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

