// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base_message.proto

package com.cotx.ovsctl.message.base;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Void)
    com.google.protobuf.MessageOrBuilder {
}
