// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: description/BridgeDescription.proto

package com.cotx.ovsctl.message.description;

public interface BridgeDescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BridgeDescription)
    com.google.protobuf.MessageOrBuilder {
}
