// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: description/PatchDescription.proto

package com.cotx.ovsctl.message.description;

public interface PatchDescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatchDescription)
    com.google.protobuf.MessageOrBuilder {
}
