// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: description/TunnelDescription.proto

package com.cotx.ovsctl.message.description;

/**
 * <pre>
 *AddTunnelModeRequest's message item.
 * </pre>
 *
 * Protobuf type {@code TunnelDescription}
 */
public  final class TunnelDescription extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TunnelDescription)
    TunnelDescriptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TunnelDescription.newBuilder() to construct.
  private TunnelDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TunnelDescription() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TunnelDescription(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TunnelDescriptionProto.internal_static_TunnelDescription_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TunnelDescriptionProto.internal_static_TunnelDescription_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TunnelDescription.class, Builder.class);
  }

  /**
   * <pre>
   *Tunnel technology type
   * </pre>
   *
   * Protobuf enum {@code TunnelDescription.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *Signifies that this is a MPLS tunnel.
     * </pre>
     *
     * <code>MPLS = 0;</code>
     */
    MPLS(0),
    /**
     * <pre>
     *Signifies that this is a L2 tunnel.
     * </pre>
     *
     * <code>VLAN = 1;</code>
     */
    VLAN(1),
    /**
     * <pre>
     *Signifies that this is a DC L2 extension tunnel.
     * </pre>
     *
     * <code>VXLAN = 2;</code>
     */
    VXLAN(2),
    /**
     * <pre>
     *Signifies that this is a L3 tunnel.
     * </pre>
     *
     * <code>GRE = 3;</code>
     */
    GRE(3),
    /**
     * <pre>
     *Signifies that this is a L1 OTN tunnel.
     * </pre>
     *
     * <code>ODUK = 4;</code>
     */
    ODUK(4),
    /**
     * <pre>
     *Signifies that this is a L0 OCH tunnel.
     * </pre>
     *
     * <code>OCH = 5;</code>
     */
    OCH(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *Signifies that this is a MPLS tunnel.
     * </pre>
     *
     * <code>MPLS = 0;</code>
     */
    public static final int MPLS_VALUE = 0;
    /**
     * <pre>
     *Signifies that this is a L2 tunnel.
     * </pre>
     *
     * <code>VLAN = 1;</code>
     */
    public static final int VLAN_VALUE = 1;
    /**
     * <pre>
     *Signifies that this is a DC L2 extension tunnel.
     * </pre>
     *
     * <code>VXLAN = 2;</code>
     */
    public static final int VXLAN_VALUE = 2;
    /**
     * <pre>
     *Signifies that this is a L3 tunnel.
     * </pre>
     *
     * <code>GRE = 3;</code>
     */
    public static final int GRE_VALUE = 3;
    /**
     * <pre>
     *Signifies that this is a L1 OTN tunnel.
     * </pre>
     *
     * <code>ODUK = 4;</code>
     */
    public static final int ODUK_VALUE = 4;
    /**
     * <pre>
     *Signifies that this is a L0 OCH tunnel.
     * </pre>
     *
     * <code>OCH = 5;</code>
     */
    public static final int OCH_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return MPLS;
        case 1: return VLAN;
        case 2: return VXLAN;
        case 3: return GRE;
        case 4: return ODUK;
        case 5: return OCH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return TunnelDescription.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TunnelDescription.Type)
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TunnelDescription)) {
      return super.equals(obj);
    }
    TunnelDescription other = (TunnelDescription) obj;

    boolean result = true;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TunnelDescription parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TunnelDescription parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TunnelDescription parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TunnelDescription parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TunnelDescription parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TunnelDescription parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TunnelDescription parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TunnelDescription parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TunnelDescription parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TunnelDescription parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TunnelDescription parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TunnelDescription parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TunnelDescription prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *AddTunnelModeRequest's message item.
   * </pre>
   *
   * Protobuf type {@code TunnelDescription}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TunnelDescription)
      TunnelDescriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TunnelDescriptionProto.internal_static_TunnelDescription_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TunnelDescriptionProto.internal_static_TunnelDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TunnelDescription.class, Builder.class);
    }

    // Construct using TunnelDescription.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TunnelDescriptionProto.internal_static_TunnelDescription_descriptor;
    }

    public TunnelDescription getDefaultInstanceForType() {
      return TunnelDescription.getDefaultInstance();
    }

    public TunnelDescription build() {
      TunnelDescription result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public TunnelDescription buildPartial() {
      TunnelDescription result = new TunnelDescription(this);
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TunnelDescription) {
        return mergeFrom((TunnelDescription)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TunnelDescription other) {
      if (other == TunnelDescription.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TunnelDescription parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TunnelDescription) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TunnelDescription)
  }

  // @@protoc_insertion_point(class_scope:TunnelDescription)
  private static final TunnelDescription DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TunnelDescription();
  }

  public static TunnelDescription getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TunnelDescription>
      PARSER = new com.google.protobuf.AbstractParser<TunnelDescription>() {
    public TunnelDescription parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TunnelDescription(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TunnelDescription> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TunnelDescription> getParserForType() {
    return PARSER;
  }

  public TunnelDescription getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

