// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/PortConfigService.proto

package com.cotx.ovsctl.message.service.portconfig;

import com.cotx.ovsctl.message.base.CommonMessageProto;
import com.cotx.ovsctl.message.common.PortNumberProto;

public final class PortConfigProto {
  private PortConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonRequestPara_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommonRequestPara_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037service/PortConfigService.proto\032\027commo" +
      "n/PortNumber.proto\032\022base_message.proto\"0" +
      "\n\021CommonRequestPara\022\033\n\006number\030\001 \001(\0132\013.Po" +
      "rtNumber2\177\n\nPortConfig\022#\n\006enable\022\022.Commo" +
      "nRequestPara\032\005.Bool\022$\n\007disable\022\022.CommonR" +
      "equestPara\032\005.Bool\022&\n\tisEnabled\022\022.CommonR" +
      "equestPara\032\005.BoolBE\n*com.cotx.ovsctl.ser" +
      "vice.message.portconfigB\017PortConfigProto" +
      "P\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PortNumberProto.getDescriptor(),
          CommonMessageProto.getDescriptor(),
        }, assigner);
    internal_static_CommonRequestPara_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommonRequestPara_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommonRequestPara_descriptor,
        new String[] { "Number", });
    PortNumberProto.getDescriptor();
    CommonMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
