// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/InterfaceConfigService.proto

package com.cotx.ovsctl.message.service.interfaceconfig;

import com.cotx.ovsctl.message.common.VlanId;
import com.cotx.ovsctl.message.common.VlanIdOrBuilder;

public interface AddAccessModeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InterfaceConfig.AddAccessModeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  boolean hasIntf();
  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  CommonField getIntf();
  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  CommonFieldOrBuilder getIntfOrBuilder();

  /**
   * <code>.VlanId vlanId = 2;</code>
   */
  boolean hasVlanId();
  /**
   * <code>.VlanId vlanId = 2;</code>
   */
  VlanId getVlanId();
  /**
   * <code>.VlanId vlanId = 2;</code>
   */
  VlanIdOrBuilder getVlanIdOrBuilder();
}
