// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/InterfaceConfigService.proto

package com.cotx.ovsctl.message.service.interfaceconfig;

import com.cotx.ovsctl.message.description.PatchDescription;
import com.cotx.ovsctl.message.description.PatchDescriptionOrBuilder;

/**
 * <pre>
 *rpc addPatchMode's request message.
 * </pre>
 *
 * Protobuf type {@code InterfaceConfig.AddPatchModeRequest}
 */
public  final class AddPatchModeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InterfaceConfig.AddPatchModeRequest)
    AddPatchModeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddPatchModeRequest.newBuilder() to construct.
  private AddPatchModeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddPatchModeRequest() {
    ifaceName_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddPatchModeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            ifaceName_ = s;
            break;
          }
          case 18: {
            PatchDescription.Builder subBuilder = null;
            if (patchInterface_ != null) {
              subBuilder = patchInterface_.toBuilder();
            }
            patchInterface_ = input.readMessage(PatchDescription.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(patchInterface_);
              patchInterface_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return InterfaceConfigProto.internal_static_InterfaceConfig_AddPatchModeRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return InterfaceConfigProto.internal_static_InterfaceConfig_AddPatchModeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AddPatchModeRequest.class, Builder.class);
  }

  public static final int IFACENAME_FIELD_NUMBER = 1;
  private volatile Object ifaceName_;
  /**
   * <code>string ifaceName = 1;</code>
   */
  public String getIfaceName() {
    Object ref = ifaceName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ifaceName_ = s;
      return s;
    }
  }
  /**
   * <code>string ifaceName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIfaceNameBytes() {
    Object ref = ifaceName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ifaceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATCHINTERFACE_FIELD_NUMBER = 2;
  private PatchDescription patchInterface_;
  /**
   * <code>.PatchDescription patchInterface = 2;</code>
   */
  public boolean hasPatchInterface() {
    return patchInterface_ != null;
  }
  /**
   * <code>.PatchDescription patchInterface = 2;</code>
   */
  public PatchDescription getPatchInterface() {
    return patchInterface_ == null ? PatchDescription.getDefaultInstance() : patchInterface_;
  }
  /**
   * <code>.PatchDescription patchInterface = 2;</code>
   */
  public PatchDescriptionOrBuilder getPatchInterfaceOrBuilder() {
    return getPatchInterface();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIfaceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ifaceName_);
    }
    if (patchInterface_ != null) {
      output.writeMessage(2, getPatchInterface());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIfaceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ifaceName_);
    }
    if (patchInterface_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPatchInterface());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AddPatchModeRequest)) {
      return super.equals(obj);
    }
    AddPatchModeRequest other = (AddPatchModeRequest) obj;

    boolean result = true;
    result = result && getIfaceName()
        .equals(other.getIfaceName());
    result = result && (hasPatchInterface() == other.hasPatchInterface());
    if (hasPatchInterface()) {
      result = result && getPatchInterface()
          .equals(other.getPatchInterface());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IFACENAME_FIELD_NUMBER;
    hash = (53 * hash) + getIfaceName().hashCode();
    if (hasPatchInterface()) {
      hash = (37 * hash) + PATCHINTERFACE_FIELD_NUMBER;
      hash = (53 * hash) + getPatchInterface().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AddPatchModeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddPatchModeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddPatchModeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddPatchModeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddPatchModeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddPatchModeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddPatchModeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddPatchModeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddPatchModeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AddPatchModeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddPatchModeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddPatchModeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AddPatchModeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *rpc addPatchMode's request message.
   * </pre>
   *
   * Protobuf type {@code InterfaceConfig.AddPatchModeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InterfaceConfig.AddPatchModeRequest)
          AddPatchModeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddPatchModeRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddPatchModeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddPatchModeRequest.class, Builder.class);
    }

    // Construct using AddPatchModeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ifaceName_ = "";

      if (patchInterfaceBuilder_ == null) {
        patchInterface_ = null;
      } else {
        patchInterface_ = null;
        patchInterfaceBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddPatchModeRequest_descriptor;
    }

    public AddPatchModeRequest getDefaultInstanceForType() {
      return AddPatchModeRequest.getDefaultInstance();
    }

    public AddPatchModeRequest build() {
      AddPatchModeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AddPatchModeRequest buildPartial() {
      AddPatchModeRequest result = new AddPatchModeRequest(this);
      result.ifaceName_ = ifaceName_;
      if (patchInterfaceBuilder_ == null) {
        result.patchInterface_ = patchInterface_;
      } else {
        result.patchInterface_ = patchInterfaceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AddPatchModeRequest) {
        return mergeFrom((AddPatchModeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AddPatchModeRequest other) {
      if (other == AddPatchModeRequest.getDefaultInstance()) return this;
      if (!other.getIfaceName().isEmpty()) {
        ifaceName_ = other.ifaceName_;
        onChanged();
      }
      if (other.hasPatchInterface()) {
        mergePatchInterface(other.getPatchInterface());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AddPatchModeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AddPatchModeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object ifaceName_ = "";
    /**
     * <code>string ifaceName = 1;</code>
     */
    public String getIfaceName() {
      Object ref = ifaceName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ifaceName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ifaceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIfaceNameBytes() {
      Object ref = ifaceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ifaceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ifaceName = 1;</code>
     */
    public Builder setIfaceName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ifaceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ifaceName = 1;</code>
     */
    public Builder clearIfaceName() {
      
      ifaceName_ = getDefaultInstance().getIfaceName();
      onChanged();
      return this;
    }
    /**
     * <code>string ifaceName = 1;</code>
     */
    public Builder setIfaceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ifaceName_ = value;
      onChanged();
      return this;
    }

    private PatchDescription patchInterface_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            PatchDescription, PatchDescription.Builder, PatchDescriptionOrBuilder> patchInterfaceBuilder_;
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    public boolean hasPatchInterface() {
      return patchInterfaceBuilder_ != null || patchInterface_ != null;
    }
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    public PatchDescription getPatchInterface() {
      if (patchInterfaceBuilder_ == null) {
        return patchInterface_ == null ? PatchDescription.getDefaultInstance() : patchInterface_;
      } else {
        return patchInterfaceBuilder_.getMessage();
      }
    }
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    public Builder setPatchInterface(PatchDescription value) {
      if (patchInterfaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        patchInterface_ = value;
        onChanged();
      } else {
        patchInterfaceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    public Builder setPatchInterface(
        PatchDescription.Builder builderForValue) {
      if (patchInterfaceBuilder_ == null) {
        patchInterface_ = builderForValue.build();
        onChanged();
      } else {
        patchInterfaceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    public Builder mergePatchInterface(PatchDescription value) {
      if (patchInterfaceBuilder_ == null) {
        if (patchInterface_ != null) {
          patchInterface_ =
            PatchDescription.newBuilder(patchInterface_).mergeFrom(value).buildPartial();
        } else {
          patchInterface_ = value;
        }
        onChanged();
      } else {
        patchInterfaceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    public Builder clearPatchInterface() {
      if (patchInterfaceBuilder_ == null) {
        patchInterface_ = null;
        onChanged();
      } else {
        patchInterface_ = null;
        patchInterfaceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    public PatchDescription.Builder getPatchInterfaceBuilder() {
      
      onChanged();
      return getPatchInterfaceFieldBuilder().getBuilder();
    }
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    public PatchDescriptionOrBuilder getPatchInterfaceOrBuilder() {
      if (patchInterfaceBuilder_ != null) {
        return patchInterfaceBuilder_.getMessageOrBuilder();
      } else {
        return patchInterface_ == null ?
            PatchDescription.getDefaultInstance() : patchInterface_;
      }
    }
    /**
     * <code>.PatchDescription patchInterface = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            PatchDescription, PatchDescription.Builder, PatchDescriptionOrBuilder>
        getPatchInterfaceFieldBuilder() {
      if (patchInterfaceBuilder_ == null) {
        patchInterfaceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                PatchDescription, PatchDescription.Builder, PatchDescriptionOrBuilder>(
                getPatchInterface(),
                getParentForChildren(),
                isClean());
        patchInterface_ = null;
      }
      return patchInterfaceBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InterfaceConfig.AddPatchModeRequest)
  }

  // @@protoc_insertion_point(class_scope:InterfaceConfig.AddPatchModeRequest)
  private static final AddPatchModeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AddPatchModeRequest();
  }

  public static AddPatchModeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddPatchModeRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddPatchModeRequest>() {
    public AddPatchModeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddPatchModeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddPatchModeRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AddPatchModeRequest> getParserForType() {
    return PARSER;
  }

  public AddPatchModeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

