// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/InterfaceConfigService.proto

package com.cotx.ovsctl.message.service.interfaceconfig;

/**
 * <pre>
 *rpc addRateLimit's request message.
 * </pre>
 *
 * Protobuf type {@code InterfaceConfig.AddRateLimitRequest}
 */
public  final class AddRateLimitRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InterfaceConfig.AddRateLimitRequest)
    AddRateLimitRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddRateLimitRequest.newBuilder() to construct.
  private AddRateLimitRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddRateLimitRequest() {
    limit_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddRateLimitRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            CommonField.Builder subBuilder = null;
            if (intf_ != null) {
              subBuilder = intf_.toBuilder();
            }
            intf_ = input.readMessage(CommonField.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(intf_);
              intf_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            limit_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return InterfaceConfigProto.internal_static_InterfaceConfig_AddRateLimitRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return InterfaceConfigProto.internal_static_InterfaceConfig_AddRateLimitRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AddRateLimitRequest.class, Builder.class);
  }

  public static final int INTF_FIELD_NUMBER = 1;
  private CommonField intf_;
  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  public boolean hasIntf() {
    return intf_ != null;
  }
  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  public CommonField getIntf() {
    return intf_ == null ? CommonField.getDefaultInstance() : intf_;
  }
  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  public CommonFieldOrBuilder getIntfOrBuilder() {
    return getIntf();
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private int limit_;
  /**
   * <code>int32 limit = 2;</code>
   */
  public int getLimit() {
    return limit_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (intf_ != null) {
      output.writeMessage(1, getIntf());
    }
    if (limit_ != 0) {
      output.writeInt32(2, limit_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (intf_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIntf());
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, limit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AddRateLimitRequest)) {
      return super.equals(obj);
    }
    AddRateLimitRequest other = (AddRateLimitRequest) obj;

    boolean result = true;
    result = result && (hasIntf() == other.hasIntf());
    if (hasIntf()) {
      result = result && getIntf()
          .equals(other.getIntf());
    }
    result = result && (getLimit()
        == other.getLimit());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIntf()) {
      hash = (37 * hash) + INTF_FIELD_NUMBER;
      hash = (53 * hash) + getIntf().hashCode();
    }
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AddRateLimitRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddRateLimitRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddRateLimitRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddRateLimitRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddRateLimitRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddRateLimitRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddRateLimitRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddRateLimitRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddRateLimitRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AddRateLimitRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddRateLimitRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddRateLimitRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AddRateLimitRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *rpc addRateLimit's request message.
   * </pre>
   *
   * Protobuf type {@code InterfaceConfig.AddRateLimitRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InterfaceConfig.AddRateLimitRequest)
          AddRateLimitRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddRateLimitRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddRateLimitRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddRateLimitRequest.class, Builder.class);
    }

    // Construct using AddRateLimitRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (intfBuilder_ == null) {
        intf_ = null;
      } else {
        intf_ = null;
        intfBuilder_ = null;
      }
      limit_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddRateLimitRequest_descriptor;
    }

    public AddRateLimitRequest getDefaultInstanceForType() {
      return AddRateLimitRequest.getDefaultInstance();
    }

    public AddRateLimitRequest build() {
      AddRateLimitRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AddRateLimitRequest buildPartial() {
      AddRateLimitRequest result = new AddRateLimitRequest(this);
      if (intfBuilder_ == null) {
        result.intf_ = intf_;
      } else {
        result.intf_ = intfBuilder_.build();
      }
      result.limit_ = limit_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AddRateLimitRequest) {
        return mergeFrom((AddRateLimitRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AddRateLimitRequest other) {
      if (other == AddRateLimitRequest.getDefaultInstance()) return this;
      if (other.hasIntf()) {
        mergeIntf(other.getIntf());
      }
      if (other.getLimit() != 0) {
        setLimit(other.getLimit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AddRateLimitRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AddRateLimitRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private CommonField intf_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            CommonField, CommonField.Builder, CommonFieldOrBuilder> intfBuilder_;
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public boolean hasIntf() {
      return intfBuilder_ != null || intf_ != null;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public CommonField getIntf() {
      if (intfBuilder_ == null) {
        return intf_ == null ? CommonField.getDefaultInstance() : intf_;
      } else {
        return intfBuilder_.getMessage();
      }
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public Builder setIntf(CommonField value) {
      if (intfBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        intf_ = value;
        onChanged();
      } else {
        intfBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public Builder setIntf(
        CommonField.Builder builderForValue) {
      if (intfBuilder_ == null) {
        intf_ = builderForValue.build();
        onChanged();
      } else {
        intfBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public Builder mergeIntf(CommonField value) {
      if (intfBuilder_ == null) {
        if (intf_ != null) {
          intf_ =
            CommonField.newBuilder(intf_).mergeFrom(value).buildPartial();
        } else {
          intf_ = value;
        }
        onChanged();
      } else {
        intfBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public Builder clearIntf() {
      if (intfBuilder_ == null) {
        intf_ = null;
        onChanged();
      } else {
        intf_ = null;
        intfBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public CommonField.Builder getIntfBuilder() {
      
      onChanged();
      return getIntfFieldBuilder().getBuilder();
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public CommonFieldOrBuilder getIntfOrBuilder() {
      if (intfBuilder_ != null) {
        return intfBuilder_.getMessageOrBuilder();
      } else {
        return intf_ == null ?
            CommonField.getDefaultInstance() : intf_;
      }
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            CommonField, CommonField.Builder, CommonFieldOrBuilder>
        getIntfFieldBuilder() {
      if (intfBuilder_ == null) {
        intfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                CommonField, CommonField.Builder, CommonFieldOrBuilder>(
                getIntf(),
                getParentForChildren(),
                isClean());
        intf_ = null;
      }
      return intfBuilder_;
    }

    private int limit_ ;
    /**
     * <code>int32 limit = 2;</code>
     */
    public int getLimit() {
      return limit_;
    }
    /**
     * <code>int32 limit = 2;</code>
     */
    public Builder setLimit(int value) {
      
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 limit = 2;</code>
     */
    public Builder clearLimit() {
      
      limit_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InterfaceConfig.AddRateLimitRequest)
  }

  // @@protoc_insertion_point(class_scope:InterfaceConfig.AddRateLimitRequest)
  private static final AddRateLimitRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AddRateLimitRequest();
  }

  public static AddRateLimitRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddRateLimitRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddRateLimitRequest>() {
    public AddRateLimitRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddRateLimitRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddRateLimitRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AddRateLimitRequest> getParserForType() {
    return PARSER;
  }

  public AddRateLimitRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

