// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/InterfaceConfigService.proto

package com.cotx.ovsctl.message.service.interfaceconfig;

import com.cotx.ovsctl.message.description.TunnelDescription;
import com.cotx.ovsctl.message.description.TunnelDescriptionOrBuilder;

/**
 * <pre>
 *rpc addTunnelMode's request message.
 * </pre>
 *
 * Protobuf type {@code InterfaceConfig.AddTunnelModeRequest}
 */
public  final class AddTunnelModeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InterfaceConfig.AddTunnelModeRequest)
    AddTunnelModeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddTunnelModeRequest.newBuilder() to construct.
  private AddTunnelModeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddTunnelModeRequest() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddTunnelModeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            CommonField.Builder subBuilder = null;
            if (intf_ != null) {
              subBuilder = intf_.toBuilder();
            }
            intf_ = input.readMessage(CommonField.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(intf_);
              intf_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            TunnelDescription.Builder subBuilder = null;
            if (tunnelDesc_ != null) {
              subBuilder = tunnelDesc_.toBuilder();
            }
            tunnelDesc_ = input.readMessage(TunnelDescription.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tunnelDesc_);
              tunnelDesc_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return InterfaceConfigProto.internal_static_InterfaceConfig_AddTunnelModeRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return InterfaceConfigProto.internal_static_InterfaceConfig_AddTunnelModeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AddTunnelModeRequest.class, Builder.class);
  }

  public static final int INTF_FIELD_NUMBER = 1;
  private CommonField intf_;
  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  public boolean hasIntf() {
    return intf_ != null;
  }
  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  public CommonField getIntf() {
    return intf_ == null ? CommonField.getDefaultInstance() : intf_;
  }
  /**
   * <code>.InterfaceConfig.CommonField intf = 1;</code>
   */
  public CommonFieldOrBuilder getIntfOrBuilder() {
    return getIntf();
  }

  public static final int TUNNELDESC_FIELD_NUMBER = 2;
  private TunnelDescription tunnelDesc_;
  /**
   * <code>.TunnelDescription tunnelDesc = 2;</code>
   */
  public boolean hasTunnelDesc() {
    return tunnelDesc_ != null;
  }
  /**
   * <code>.TunnelDescription tunnelDesc = 2;</code>
   */
  public TunnelDescription getTunnelDesc() {
    return tunnelDesc_ == null ? TunnelDescription.getDefaultInstance() : tunnelDesc_;
  }
  /**
   * <code>.TunnelDescription tunnelDesc = 2;</code>
   */
  public TunnelDescriptionOrBuilder getTunnelDescOrBuilder() {
    return getTunnelDesc();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (intf_ != null) {
      output.writeMessage(1, getIntf());
    }
    if (tunnelDesc_ != null) {
      output.writeMessage(2, getTunnelDesc());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (intf_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIntf());
    }
    if (tunnelDesc_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTunnelDesc());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AddTunnelModeRequest)) {
      return super.equals(obj);
    }
    AddTunnelModeRequest other = (AddTunnelModeRequest) obj;

    boolean result = true;
    result = result && (hasIntf() == other.hasIntf());
    if (hasIntf()) {
      result = result && getIntf()
          .equals(other.getIntf());
    }
    result = result && (hasTunnelDesc() == other.hasTunnelDesc());
    if (hasTunnelDesc()) {
      result = result && getTunnelDesc()
          .equals(other.getTunnelDesc());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIntf()) {
      hash = (37 * hash) + INTF_FIELD_NUMBER;
      hash = (53 * hash) + getIntf().hashCode();
    }
    if (hasTunnelDesc()) {
      hash = (37 * hash) + TUNNELDESC_FIELD_NUMBER;
      hash = (53 * hash) + getTunnelDesc().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AddTunnelModeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddTunnelModeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddTunnelModeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddTunnelModeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddTunnelModeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddTunnelModeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddTunnelModeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddTunnelModeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddTunnelModeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AddTunnelModeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddTunnelModeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddTunnelModeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AddTunnelModeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *rpc addTunnelMode's request message.
   * </pre>
   *
   * Protobuf type {@code InterfaceConfig.AddTunnelModeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InterfaceConfig.AddTunnelModeRequest)
          AddTunnelModeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddTunnelModeRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddTunnelModeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddTunnelModeRequest.class, Builder.class);
    }

    // Construct using AddTunnelModeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (intfBuilder_ == null) {
        intf_ = null;
      } else {
        intf_ = null;
        intfBuilder_ = null;
      }
      if (tunnelDescBuilder_ == null) {
        tunnelDesc_ = null;
      } else {
        tunnelDesc_ = null;
        tunnelDescBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_AddTunnelModeRequest_descriptor;
    }

    public AddTunnelModeRequest getDefaultInstanceForType() {
      return AddTunnelModeRequest.getDefaultInstance();
    }

    public AddTunnelModeRequest build() {
      AddTunnelModeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AddTunnelModeRequest buildPartial() {
      AddTunnelModeRequest result = new AddTunnelModeRequest(this);
      if (intfBuilder_ == null) {
        result.intf_ = intf_;
      } else {
        result.intf_ = intfBuilder_.build();
      }
      if (tunnelDescBuilder_ == null) {
        result.tunnelDesc_ = tunnelDesc_;
      } else {
        result.tunnelDesc_ = tunnelDescBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AddTunnelModeRequest) {
        return mergeFrom((AddTunnelModeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AddTunnelModeRequest other) {
      if (other == AddTunnelModeRequest.getDefaultInstance()) return this;
      if (other.hasIntf()) {
        mergeIntf(other.getIntf());
      }
      if (other.hasTunnelDesc()) {
        mergeTunnelDesc(other.getTunnelDesc());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AddTunnelModeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AddTunnelModeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private CommonField intf_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            CommonField, CommonField.Builder, CommonFieldOrBuilder> intfBuilder_;
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public boolean hasIntf() {
      return intfBuilder_ != null || intf_ != null;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public CommonField getIntf() {
      if (intfBuilder_ == null) {
        return intf_ == null ? CommonField.getDefaultInstance() : intf_;
      } else {
        return intfBuilder_.getMessage();
      }
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public Builder setIntf(CommonField value) {
      if (intfBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        intf_ = value;
        onChanged();
      } else {
        intfBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public Builder setIntf(
        CommonField.Builder builderForValue) {
      if (intfBuilder_ == null) {
        intf_ = builderForValue.build();
        onChanged();
      } else {
        intfBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public Builder mergeIntf(CommonField value) {
      if (intfBuilder_ == null) {
        if (intf_ != null) {
          intf_ =
            CommonField.newBuilder(intf_).mergeFrom(value).buildPartial();
        } else {
          intf_ = value;
        }
        onChanged();
      } else {
        intfBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public Builder clearIntf() {
      if (intfBuilder_ == null) {
        intf_ = null;
        onChanged();
      } else {
        intf_ = null;
        intfBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public CommonField.Builder getIntfBuilder() {
      
      onChanged();
      return getIntfFieldBuilder().getBuilder();
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    public CommonFieldOrBuilder getIntfOrBuilder() {
      if (intfBuilder_ != null) {
        return intfBuilder_.getMessageOrBuilder();
      } else {
        return intf_ == null ?
            CommonField.getDefaultInstance() : intf_;
      }
    }
    /**
     * <code>.InterfaceConfig.CommonField intf = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            CommonField, CommonField.Builder, CommonFieldOrBuilder>
        getIntfFieldBuilder() {
      if (intfBuilder_ == null) {
        intfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                CommonField, CommonField.Builder, CommonFieldOrBuilder>(
                getIntf(),
                getParentForChildren(),
                isClean());
        intf_ = null;
      }
      return intfBuilder_;
    }

    private TunnelDescription tunnelDesc_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            TunnelDescription, TunnelDescription.Builder, TunnelDescriptionOrBuilder> tunnelDescBuilder_;
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    public boolean hasTunnelDesc() {
      return tunnelDescBuilder_ != null || tunnelDesc_ != null;
    }
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    public TunnelDescription getTunnelDesc() {
      if (tunnelDescBuilder_ == null) {
        return tunnelDesc_ == null ? TunnelDescription.getDefaultInstance() : tunnelDesc_;
      } else {
        return tunnelDescBuilder_.getMessage();
      }
    }
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    public Builder setTunnelDesc(TunnelDescription value) {
      if (tunnelDescBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tunnelDesc_ = value;
        onChanged();
      } else {
        tunnelDescBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    public Builder setTunnelDesc(
        TunnelDescription.Builder builderForValue) {
      if (tunnelDescBuilder_ == null) {
        tunnelDesc_ = builderForValue.build();
        onChanged();
      } else {
        tunnelDescBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    public Builder mergeTunnelDesc(TunnelDescription value) {
      if (tunnelDescBuilder_ == null) {
        if (tunnelDesc_ != null) {
          tunnelDesc_ =
            TunnelDescription.newBuilder(tunnelDesc_).mergeFrom(value).buildPartial();
        } else {
          tunnelDesc_ = value;
        }
        onChanged();
      } else {
        tunnelDescBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    public Builder clearTunnelDesc() {
      if (tunnelDescBuilder_ == null) {
        tunnelDesc_ = null;
        onChanged();
      } else {
        tunnelDesc_ = null;
        tunnelDescBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    public TunnelDescription.Builder getTunnelDescBuilder() {
      
      onChanged();
      return getTunnelDescFieldBuilder().getBuilder();
    }
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    public TunnelDescriptionOrBuilder getTunnelDescOrBuilder() {
      if (tunnelDescBuilder_ != null) {
        return tunnelDescBuilder_.getMessageOrBuilder();
      } else {
        return tunnelDesc_ == null ?
            TunnelDescription.getDefaultInstance() : tunnelDesc_;
      }
    }
    /**
     * <code>.TunnelDescription tunnelDesc = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            TunnelDescription, TunnelDescription.Builder, TunnelDescriptionOrBuilder>
        getTunnelDescFieldBuilder() {
      if (tunnelDescBuilder_ == null) {
        tunnelDescBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                TunnelDescription, TunnelDescription.Builder, TunnelDescriptionOrBuilder>(
                getTunnelDesc(),
                getParentForChildren(),
                isClean());
        tunnelDesc_ = null;
      }
      return tunnelDescBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InterfaceConfig.AddTunnelModeRequest)
  }

  // @@protoc_insertion_point(class_scope:InterfaceConfig.AddTunnelModeRequest)
  private static final AddTunnelModeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AddTunnelModeRequest();
  }

  public static AddTunnelModeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddTunnelModeRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddTunnelModeRequest>() {
    public AddTunnelModeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddTunnelModeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddTunnelModeRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AddTunnelModeRequest> getParserForType() {
    return PARSER;
  }

  public AddTunnelModeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

