// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/InterfaceConfigService.proto

package com.cotx.ovsctl.message.service.interfaceconfig;

/**
 * <pre>
 *1. service interface's common field
 *2. rpc removeAccessMode's request message.
 *3. AddAccessModeRequest's message item.
 *4. AddTrunkModeRequest's message item.
 *5. rpc removeTrunkMode's request message.
 *6. AddRateLimitRequest's message item.
 *7. rpc CommonField's request message.
 *8. AddTunnelModeRequest's message item.
 *9. removeTunnelMode's request message.
 * </pre>
 *
 * Protobuf type {@code InterfaceConfig.CommonField}
 */
public  final class CommonField extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InterfaceConfig.CommonField)
    CommonFieldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommonField.newBuilder() to construct.
  private CommonField(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommonField() {
    intf_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommonField(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            intf_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return InterfaceConfigProto.internal_static_InterfaceConfig_CommonField_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return InterfaceConfigProto.internal_static_InterfaceConfig_CommonField_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CommonField.class, Builder.class);
  }

  public static final int INTF_FIELD_NUMBER = 1;
  private volatile Object intf_;
  /**
   * <code>string intf = 1;</code>
   */
  public String getIntf() {
    Object ref = intf_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      intf_ = s;
      return s;
    }
  }
  /**
   * <code>string intf = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIntfBytes() {
    Object ref = intf_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      intf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIntfBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, intf_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIntfBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, intf_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CommonField)) {
      return super.equals(obj);
    }
    CommonField other = (CommonField) obj;

    boolean result = true;
    result = result && getIntf()
        .equals(other.getIntf());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INTF_FIELD_NUMBER;
    hash = (53 * hash) + getIntf().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CommonField parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommonField parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommonField parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommonField parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommonField parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommonField parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommonField parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CommonField parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CommonField parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CommonField parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CommonField parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CommonField parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CommonField prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *1. service interface's common field
   *2. rpc removeAccessMode's request message.
   *3. AddAccessModeRequest's message item.
   *4. AddTrunkModeRequest's message item.
   *5. rpc removeTrunkMode's request message.
   *6. AddRateLimitRequest's message item.
   *7. rpc CommonField's request message.
   *8. AddTunnelModeRequest's message item.
   *9. removeTunnelMode's request message.
   * </pre>
   *
   * Protobuf type {@code InterfaceConfig.CommonField}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InterfaceConfig.CommonField)
          CommonFieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_CommonField_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_CommonField_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommonField.class, Builder.class);
    }

    // Construct using CommonField.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      intf_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return InterfaceConfigProto.internal_static_InterfaceConfig_CommonField_descriptor;
    }

    public CommonField getDefaultInstanceForType() {
      return CommonField.getDefaultInstance();
    }

    public CommonField build() {
      CommonField result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public CommonField buildPartial() {
      CommonField result = new CommonField(this);
      result.intf_ = intf_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CommonField) {
        return mergeFrom((CommonField)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CommonField other) {
      if (other == CommonField.getDefaultInstance()) return this;
      if (!other.getIntf().isEmpty()) {
        intf_ = other.intf_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CommonField parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CommonField) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object intf_ = "";
    /**
     * <code>string intf = 1;</code>
     */
    public String getIntf() {
      Object ref = intf_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        intf_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string intf = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIntfBytes() {
      Object ref = intf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        intf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string intf = 1;</code>
     */
    public Builder setIntf(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      intf_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string intf = 1;</code>
     */
    public Builder clearIntf() {
      
      intf_ = getDefaultInstance().getIntf();
      onChanged();
      return this;
    }
    /**
     * <code>string intf = 1;</code>
     */
    public Builder setIntfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      intf_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InterfaceConfig.CommonField)
  }

  // @@protoc_insertion_point(class_scope:InterfaceConfig.CommonField)
  private static final CommonField DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CommonField();
  }

  public static CommonField getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommonField>
      PARSER = new com.google.protobuf.AbstractParser<CommonField>() {
    public CommonField parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommonField(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommonField> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CommonField> getParserForType() {
    return PARSER;
  }

  public CommonField getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

