// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/InterfaceConfigService.proto

package com.cotx.ovsctl.message.service.interfaceconfig;

public interface CommonFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InterfaceConfig.CommonField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string intf = 1;</code>
   */
  String getIntf();
  /**
   * <code>string intf = 1;</code>
   */
  com.google.protobuf.ByteString
      getIntfBytes();
}
