// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/ControllProtocolVersion.proto

package com.cotx.ovsctl.message.common;

/**
 * <pre>
 *1. define ControlProtocolVersion message type.
 *2. OvsBridge's message item.
 * </pre>
 *
 * Protobuf enum {@code ControlProtocolVersion}
 */
public enum ControlProtocolVersion
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *OF_1_0("OpenFlow10"),
   *OF_1_1("OpenFlow11"),
   *OF_1_2("OpenFlow12"),
   *OF_1_3("OpenFlow13"),
   *OF_1_4("OpenFlow14"),
   *OF_1_5("OpenFlow15");
   * </pre>
   *
   * <code>OF_1_0 = 0;</code>
   */
  OF_1_0(0),
  /**
   * <code>OF_1_1 = 1;</code>
   */
  OF_1_1(1),
  /**
   * <code>OF_1_2 = 2;</code>
   */
  OF_1_2(2),
  /**
   * <code>OF_1_3 = 3;</code>
   */
  OF_1_3(3),
  /**
   * <code>OF_1_4 = 4;</code>
   */
  OF_1_4(4),
  /**
   * <code>OF_1_5 = 5;</code>
   */
  OF_1_5(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *OF_1_0("OpenFlow10"),
   *OF_1_1("OpenFlow11"),
   *OF_1_2("OpenFlow12"),
   *OF_1_3("OpenFlow13"),
   *OF_1_4("OpenFlow14"),
   *OF_1_5("OpenFlow15");
   * </pre>
   *
   * <code>OF_1_0 = 0;</code>
   */
  public static final int OF_1_0_VALUE = 0;
  /**
   * <code>OF_1_1 = 1;</code>
   */
  public static final int OF_1_1_VALUE = 1;
  /**
   * <code>OF_1_2 = 2;</code>
   */
  public static final int OF_1_2_VALUE = 2;
  /**
   * <code>OF_1_3 = 3;</code>
   */
  public static final int OF_1_3_VALUE = 3;
  /**
   * <code>OF_1_4 = 4;</code>
   */
  public static final int OF_1_4_VALUE = 4;
  /**
   * <code>OF_1_5 = 5;</code>
   */
  public static final int OF_1_5_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ControlProtocolVersion valueOf(int value) {
    return forNumber(value);
  }

  public static ControlProtocolVersion forNumber(int value) {
    switch (value) {
      case 0: return OF_1_0;
      case 1: return OF_1_1;
      case 2: return OF_1_2;
      case 3: return OF_1_3;
      case 4: return OF_1_4;
      case 5: return OF_1_5;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ControlProtocolVersion>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ControlProtocolVersion> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ControlProtocolVersion>() {
          public ControlProtocolVersion findValueByNumber(int number) {
            return ControlProtocolVersion.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ControlProtocolVersionProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ControlProtocolVersion[] VALUES = values();

  public static ControlProtocolVersion valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ControlProtocolVersion(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ControlProtocolVersion)
}

