// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/PortNumber.proto

package com.cotx.ovsctl.message.common;

public interface PortNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PortNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 number = 1;</code>
   */
  long getNumber();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool hasName = 3;</code>
   */
  boolean getHasName();
}
