// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/SwitchConfigService.proto

package com.cotx.ovsctl.message.service.switchconfig;

import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsBridge;
import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsBridgeOrBuilder;

/**
 * <pre>
 *rpc addBridge's request message.
 * </pre>
 *
 * Protobuf type {@code AddBridgeRequest}
 */
public  final class AddBridgeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AddBridgeRequest)
    AddBridgeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddBridgeRequest.newBuilder() to construct.
  private AddBridgeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddBridgeRequest() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddBridgeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            OvsBridge.Builder subBuilder = null;
            if (bridge_ != null) {
              subBuilder = bridge_.toBuilder();
            }
            bridge_ = input.readMessage(OvsBridge.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bridge_);
              bridge_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SwitchConfigProto.internal_static_AddBridgeRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SwitchConfigProto.internal_static_AddBridgeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AddBridgeRequest.class, Builder.class);
  }

  public static final int BRIDGE_FIELD_NUMBER = 1;
  private OvsBridge bridge_;
  /**
   * <code>.OvsBridge bridge = 1;</code>
   */
  public boolean hasBridge() {
    return bridge_ != null;
  }
  /**
   * <code>.OvsBridge bridge = 1;</code>
   */
  public OvsBridge getBridge() {
    return bridge_ == null ? OvsBridge.getDefaultInstance() : bridge_;
  }
  /**
   * <code>.OvsBridge bridge = 1;</code>
   */
  public OvsBridgeOrBuilder getBridgeOrBuilder() {
    return getBridge();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasBridge()) {
      if (!getBridge().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bridge_ != null) {
      output.writeMessage(1, getBridge());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bridge_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBridge());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AddBridgeRequest)) {
      return super.equals(obj);
    }
    AddBridgeRequest other = (AddBridgeRequest) obj;

    boolean result = true;
    result = result && (hasBridge() == other.hasBridge());
    if (hasBridge()) {
      result = result && getBridge()
          .equals(other.getBridge());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBridge()) {
      hash = (37 * hash) + BRIDGE_FIELD_NUMBER;
      hash = (53 * hash) + getBridge().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AddBridgeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddBridgeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddBridgeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddBridgeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddBridgeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddBridgeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddBridgeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddBridgeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddBridgeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AddBridgeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddBridgeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AddBridgeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AddBridgeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *rpc addBridge's request message.
   * </pre>
   *
   * Protobuf type {@code AddBridgeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AddBridgeRequest)
          AddBridgeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SwitchConfigProto.internal_static_AddBridgeRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SwitchConfigProto.internal_static_AddBridgeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddBridgeRequest.class, Builder.class);
    }

    // Construct using AddBridgeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (bridgeBuilder_ == null) {
        bridge_ = null;
      } else {
        bridge_ = null;
        bridgeBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SwitchConfigProto.internal_static_AddBridgeRequest_descriptor;
    }

    public AddBridgeRequest getDefaultInstanceForType() {
      return AddBridgeRequest.getDefaultInstance();
    }

    public AddBridgeRequest build() {
      AddBridgeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AddBridgeRequest buildPartial() {
      AddBridgeRequest result = new AddBridgeRequest(this);
      if (bridgeBuilder_ == null) {
        result.bridge_ = bridge_;
      } else {
        result.bridge_ = bridgeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AddBridgeRequest) {
        return mergeFrom((AddBridgeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AddBridgeRequest other) {
      if (other == AddBridgeRequest.getDefaultInstance()) return this;
      if (other.hasBridge()) {
        mergeBridge(other.getBridge());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (hasBridge()) {
        if (!getBridge().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AddBridgeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AddBridgeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private OvsBridge bridge_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            OvsBridge, OvsBridge.Builder, OvsBridgeOrBuilder> bridgeBuilder_;
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    public boolean hasBridge() {
      return bridgeBuilder_ != null || bridge_ != null;
    }
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    public OvsBridge getBridge() {
      if (bridgeBuilder_ == null) {
        return bridge_ == null ? OvsBridge.getDefaultInstance() : bridge_;
      } else {
        return bridgeBuilder_.getMessage();
      }
    }
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    public Builder setBridge(OvsBridge value) {
      if (bridgeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bridge_ = value;
        onChanged();
      } else {
        bridgeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    public Builder setBridge(
        OvsBridge.Builder builderForValue) {
      if (bridgeBuilder_ == null) {
        bridge_ = builderForValue.build();
        onChanged();
      } else {
        bridgeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    public Builder mergeBridge(OvsBridge value) {
      if (bridgeBuilder_ == null) {
        if (bridge_ != null) {
          bridge_ =
            OvsBridge.newBuilder(bridge_).mergeFrom(value).buildPartial();
        } else {
          bridge_ = value;
        }
        onChanged();
      } else {
        bridgeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    public Builder clearBridge() {
      if (bridgeBuilder_ == null) {
        bridge_ = null;
        onChanged();
      } else {
        bridge_ = null;
        bridgeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    public OvsBridge.Builder getBridgeBuilder() {
      
      onChanged();
      return getBridgeFieldBuilder().getBuilder();
    }
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    public OvsBridgeOrBuilder getBridgeOrBuilder() {
      if (bridgeBuilder_ != null) {
        return bridgeBuilder_.getMessageOrBuilder();
      } else {
        return bridge_ == null ?
            OvsBridge.getDefaultInstance() : bridge_;
      }
    }
    /**
     * <code>.OvsBridge bridge = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            OvsBridge, OvsBridge.Builder, OvsBridgeOrBuilder>
        getBridgeFieldBuilder() {
      if (bridgeBuilder_ == null) {
        bridgeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                OvsBridge, OvsBridge.Builder, OvsBridgeOrBuilder>(
                getBridge(),
                getParentForChildren(),
                isClean());
        bridge_ = null;
      }
      return bridgeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AddBridgeRequest)
  }

  // @@protoc_insertion_point(class_scope:AddBridgeRequest)
  private static final AddBridgeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AddBridgeRequest();
  }

  public static AddBridgeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddBridgeRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddBridgeRequest>() {
    public AddBridgeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddBridgeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddBridgeRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AddBridgeRequest> getParserForType() {
    return PARSER;
  }

  public AddBridgeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

