// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/SwitchConfigService.proto

package com.cotx.ovsctl.message.service.switchconfig;

import com.cotx.ovsctl.message.base.CommonMessageProto;
import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsBridgeProto;

public final class SwitchConfigProto {
  private SwitchConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddBridgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddBridgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BridgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BridgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBridgeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBridgeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetBridgesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetBridgesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!service/SwitchConfigService.proto\032\036ovs" +
      "db/ovs/core/OvsBridge.proto\032\022base_messag" +
      "e.proto\".\n\020AddBridgeRequest\022\032\n\006bridge\030\001 " +
      "\001(\0132\n.OvsBridge\"#\n\rBridgeRequest\022\022\n\nbrid" +
      "geDpid\030\001 \001(\t\"2\n\021GetBridgeResponse\022\035\n\tovs" +
      "Bridge\030\001 \001(\0132\n.OvsBridge\"3\n\022GetBridgesRe" +
      "sponse\022\035\n\tovsBridge\030\001 \003(\0132\n.OvsBridge2\267\001" +
      "\n\014SwitchConfig\022%\n\taddBridge\022\021.AddBridgeR" +
      "equest\032\005.Bool\022%\n\014deleteBridge\022\016.BridgeRe" +
      "quest\032\005.Bool\022/\n\tgetBridge\022\016.BridgeReques" +
      "t\032\022.GetBridgeResponse\022(\n\ngetBridges\022\005.Vo" +
      "id\032\023.GetBridgesResponseBI\n,com.cotx.ovsc" +
      "tl.service.message.switchconfigB\021SwitchC" +
      "onfigProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          OvsBridgeProto.getDescriptor(),
          CommonMessageProto.getDescriptor(),
        }, assigner);
    internal_static_AddBridgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddBridgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddBridgeRequest_descriptor,
        new String[] { "Bridge", });
    internal_static_BridgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BridgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BridgeRequest_descriptor,
        new String[] { "BridgeDpid", });
    internal_static_GetBridgeResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetBridgeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBridgeResponse_descriptor,
        new String[] { "OvsBridge", });
    internal_static_GetBridgesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetBridgesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetBridgesResponse_descriptor,
        new String[] { "OvsBridge", });
    OvsBridgeProto.getDescriptor();
    CommonMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
