// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsController;
import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsControllerOrBuilder;

public interface AddControllerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BridgeConfig.AddControllerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  boolean hasBridgeName();
  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  CommonField getBridgeName();
  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  CommonFieldOrBuilder getBridgeNameOrBuilder();

  /**
   * <code>.OvsController controller = 2;</code>
   */
  boolean hasController();
  /**
   * <code>.OvsController controller = 2;</code>
   */
  OvsController getController();
  /**
   * <code>.OvsController controller = 2;</code>
   */
  OvsControllerOrBuilder getControllerOrBuilder();
}
