// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsInterface;
import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsInterfaceOrBuilder;

public interface AddInterfaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BridgeConfig.AddInterfaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  boolean hasPortRequest();
  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  PortRequest getPortRequest();
  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  PortRequestOrBuilder getPortRequestOrBuilder();

  /**
   * <code>.OvsInterface ovsInterface = 2;</code>
   */
  boolean hasOvsInterface();
  /**
   * <code>.OvsInterface ovsInterface = 2;</code>
   */
  OvsInterface getOvsInterface();
  /**
   * <code>.OvsInterface ovsInterface = 2;</code>
   */
  OvsInterfaceOrBuilder getOvsInterfaceOrBuilder();
}
