// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

import com.cotx.ovsctl.message.description.TunnelDescription;
import com.cotx.ovsctl.message.description.TunnelDescriptionOrBuilder;
import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsPort;
import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsPortOrBuilder;

public interface AddTunnelPortRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BridgeConfig.AddTunnelPortRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  boolean hasBridgeName();
  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  CommonField getBridgeName();
  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  CommonFieldOrBuilder getBridgeNameOrBuilder();

  /**
   * <code>.OvsPort ovsPort = 2;</code>
   */
  boolean hasOvsPort();
  /**
   * <code>.OvsPort ovsPort = 2;</code>
   */
  OvsPort getOvsPort();
  /**
   * <code>.OvsPort ovsPort = 2;</code>
   */
  OvsPortOrBuilder getOvsPortOrBuilder();

  /**
   * <code>.TunnelDescription tunnelDescription = 3;</code>
   */
  boolean hasTunnelDescription();
  /**
   * <code>.TunnelDescription tunnelDescription = 3;</code>
   */
  TunnelDescription getTunnelDescription();
  /**
   * <code>.TunnelDescription tunnelDescription = 3;</code>
   */
  TunnelDescriptionOrBuilder getTunnelDescriptionOrBuilder();
}
