// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

public interface CommonFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BridgeConfig.CommonField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bridgeName = 1;</code>
   */
  String getBridgeName();
  /**
   * <code>string bridgeName = 1;</code>
   */
  com.google.protobuf.ByteString
      getBridgeNameBytes();
}
