// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

public interface DeleteControllerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BridgeConfig.DeleteControllerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  boolean hasBridgeName();
  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  CommonField getBridgeName();
  /**
   * <code>.BridgeConfig.CommonField bridgeName = 1;</code>
   */
  CommonFieldOrBuilder getBridgeNameOrBuilder();

  /**
   * <code>string controllerTarget = 2;</code>
   */
  String getControllerTarget();
  /**
   * <code>string controllerTarget = 2;</code>
   */
  com.google.protobuf.ByteString
      getControllerTargetBytes();
}
