// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsPort;
import com.cotx.ovsctl.message.ovsdb.ovs.core.OvsPortOrBuilder;

public interface GetPortsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BridgeConfig.GetPortsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .OvsPort ovsPort = 1;</code>
   */
  java.util.List<OvsPort>
      getOvsPortList();
  /**
   * <code>repeated .OvsPort ovsPort = 1;</code>
   */
  OvsPort getOvsPort(int index);
  /**
   * <code>repeated .OvsPort ovsPort = 1;</code>
   */
  int getOvsPortCount();
  /**
   * <code>repeated .OvsPort ovsPort = 1;</code>
   */
  java.util.List<? extends OvsPortOrBuilder>
      getOvsPortOrBuilderList();
  /**
   * <code>repeated .OvsPort ovsPort = 1;</code>
   */
  OvsPortOrBuilder getOvsPortOrBuilder(
          int index);
}
