// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

/**
 * <pre>
 *1. rpc getInterface's requset message.
 *2. rpc deleteInterface's request message.
 * </pre>
 *
 * Protobuf type {@code BridgeConfig.InterfaceRequest}
 */
public  final class InterfaceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BridgeConfig.InterfaceRequest)
    InterfaceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InterfaceRequest.newBuilder() to construct.
  private InterfaceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InterfaceRequest() {
    infUuid_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InterfaceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            PortRequest.Builder subBuilder = null;
            if (portRequest_ != null) {
              subBuilder = portRequest_.toBuilder();
            }
            portRequest_ = input.readMessage(PortRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(portRequest_);
              portRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            infUuid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BridgeConfigProto.internal_static_BridgeConfig_InterfaceRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BridgeConfigProto.internal_static_BridgeConfig_InterfaceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            InterfaceRequest.class, Builder.class);
  }

  public static final int PORTREQUEST_FIELD_NUMBER = 1;
  private PortRequest portRequest_;
  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  public boolean hasPortRequest() {
    return portRequest_ != null;
  }
  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  public PortRequest getPortRequest() {
    return portRequest_ == null ? PortRequest.getDefaultInstance() : portRequest_;
  }
  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  public PortRequestOrBuilder getPortRequestOrBuilder() {
    return getPortRequest();
  }

  public static final int INFUUID_FIELD_NUMBER = 2;
  private volatile Object infUuid_;
  /**
   * <code>string infUuid = 2;</code>
   */
  public String getInfUuid() {
    Object ref = infUuid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      infUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string infUuid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getInfUuidBytes() {
    Object ref = infUuid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      infUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (portRequest_ != null) {
      output.writeMessage(1, getPortRequest());
    }
    if (!getInfUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, infUuid_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (portRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPortRequest());
    }
    if (!getInfUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, infUuid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof InterfaceRequest)) {
      return super.equals(obj);
    }
    InterfaceRequest other = (InterfaceRequest) obj;

    boolean result = true;
    result = result && (hasPortRequest() == other.hasPortRequest());
    if (hasPortRequest()) {
      result = result && getPortRequest()
          .equals(other.getPortRequest());
    }
    result = result && getInfUuid()
        .equals(other.getInfUuid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPortRequest()) {
      hash = (37 * hash) + PORTREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getPortRequest().hashCode();
    }
    hash = (37 * hash) + INFUUID_FIELD_NUMBER;
    hash = (53 * hash) + getInfUuid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static InterfaceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InterfaceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InterfaceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InterfaceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InterfaceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InterfaceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InterfaceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InterfaceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static InterfaceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static InterfaceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static InterfaceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InterfaceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(InterfaceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *1. rpc getInterface's requset message.
   *2. rpc deleteInterface's request message.
   * </pre>
   *
   * Protobuf type {@code BridgeConfig.InterfaceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BridgeConfig.InterfaceRequest)
          InterfaceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BridgeConfigProto.internal_static_BridgeConfig_InterfaceRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BridgeConfigProto.internal_static_BridgeConfig_InterfaceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InterfaceRequest.class, Builder.class);
    }

    // Construct using InterfaceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (portRequestBuilder_ == null) {
        portRequest_ = null;
      } else {
        portRequest_ = null;
        portRequestBuilder_ = null;
      }
      infUuid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BridgeConfigProto.internal_static_BridgeConfig_InterfaceRequest_descriptor;
    }

    public InterfaceRequest getDefaultInstanceForType() {
      return InterfaceRequest.getDefaultInstance();
    }

    public InterfaceRequest build() {
      InterfaceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public InterfaceRequest buildPartial() {
      InterfaceRequest result = new InterfaceRequest(this);
      if (portRequestBuilder_ == null) {
        result.portRequest_ = portRequest_;
      } else {
        result.portRequest_ = portRequestBuilder_.build();
      }
      result.infUuid_ = infUuid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof InterfaceRequest) {
        return mergeFrom((InterfaceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(InterfaceRequest other) {
      if (other == InterfaceRequest.getDefaultInstance()) return this;
      if (other.hasPortRequest()) {
        mergePortRequest(other.getPortRequest());
      }
      if (!other.getInfUuid().isEmpty()) {
        infUuid_ = other.infUuid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      InterfaceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (InterfaceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private PortRequest portRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            PortRequest, PortRequest.Builder, PortRequestOrBuilder> portRequestBuilder_;
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    public boolean hasPortRequest() {
      return portRequestBuilder_ != null || portRequest_ != null;
    }
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    public PortRequest getPortRequest() {
      if (portRequestBuilder_ == null) {
        return portRequest_ == null ? PortRequest.getDefaultInstance() : portRequest_;
      } else {
        return portRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    public Builder setPortRequest(PortRequest value) {
      if (portRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        portRequest_ = value;
        onChanged();
      } else {
        portRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    public Builder setPortRequest(
        PortRequest.Builder builderForValue) {
      if (portRequestBuilder_ == null) {
        portRequest_ = builderForValue.build();
        onChanged();
      } else {
        portRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    public Builder mergePortRequest(PortRequest value) {
      if (portRequestBuilder_ == null) {
        if (portRequest_ != null) {
          portRequest_ =
            PortRequest.newBuilder(portRequest_).mergeFrom(value).buildPartial();
        } else {
          portRequest_ = value;
        }
        onChanged();
      } else {
        portRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    public Builder clearPortRequest() {
      if (portRequestBuilder_ == null) {
        portRequest_ = null;
        onChanged();
      } else {
        portRequest_ = null;
        portRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    public PortRequest.Builder getPortRequestBuilder() {
      
      onChanged();
      return getPortRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    public PortRequestOrBuilder getPortRequestOrBuilder() {
      if (portRequestBuilder_ != null) {
        return portRequestBuilder_.getMessageOrBuilder();
      } else {
        return portRequest_ == null ?
            PortRequest.getDefaultInstance() : portRequest_;
      }
    }
    /**
     * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            PortRequest, PortRequest.Builder, PortRequestOrBuilder>
        getPortRequestFieldBuilder() {
      if (portRequestBuilder_ == null) {
        portRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                PortRequest, PortRequest.Builder, PortRequestOrBuilder>(
                getPortRequest(),
                getParentForChildren(),
                isClean());
        portRequest_ = null;
      }
      return portRequestBuilder_;
    }

    private Object infUuid_ = "";
    /**
     * <code>string infUuid = 2;</code>
     */
    public String getInfUuid() {
      Object ref = infUuid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        infUuid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string infUuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInfUuidBytes() {
      Object ref = infUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        infUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string infUuid = 2;</code>
     */
    public Builder setInfUuid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      infUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string infUuid = 2;</code>
     */
    public Builder clearInfUuid() {
      
      infUuid_ = getDefaultInstance().getInfUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string infUuid = 2;</code>
     */
    public Builder setInfUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      infUuid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BridgeConfig.InterfaceRequest)
  }

  // @@protoc_insertion_point(class_scope:BridgeConfig.InterfaceRequest)
  private static final InterfaceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InterfaceRequest();
  }

  public static InterfaceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InterfaceRequest>
      PARSER = new com.google.protobuf.AbstractParser<InterfaceRequest>() {
    public InterfaceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InterfaceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InterfaceRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<InterfaceRequest> getParserForType() {
    return PARSER;
  }

  public InterfaceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

