// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

public interface InterfaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BridgeConfig.InterfaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  boolean hasPortRequest();
  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  PortRequest getPortRequest();
  /**
   * <code>.BridgeConfig.PortRequest portRequest = 1;</code>
   */
  PortRequestOrBuilder getPortRequestOrBuilder();

  /**
   * <code>string infUuid = 2;</code>
   */
  String getInfUuid();
  /**
   * <code>string infUuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getInfUuidBytes();
}
