// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/BridgeConfigService.proto

package com.cotx.ovsctl.message.service.bridgeconfig;

/**
 * <pre>
 *1. rpc deletePort's request message.
 *2. rpc getPortByUuid's request message.
 *3. rpc getInterfaces's request message.
 *4. InterfaceRequest's message item.
 *5. AddInterfaceRequest's message item.
 * </pre>
 *
 * Protobuf type {@code BridgeConfig.PortRequest}
 */
public  final class PortRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BridgeConfig.PortRequest)
    PortRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PortRequest.newBuilder() to construct.
  private PortRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PortRequest() {
    bridgeDpid_ = "";
    portUuid_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PortRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            bridgeDpid_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            portUuid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BridgeConfigProto.internal_static_BridgeConfig_PortRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BridgeConfigProto.internal_static_BridgeConfig_PortRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PortRequest.class, Builder.class);
  }

  public static final int BRIDGEDPID_FIELD_NUMBER = 1;
  private volatile Object bridgeDpid_;
  /**
   * <code>string bridgeDpid = 1;</code>
   */
  public String getBridgeDpid() {
    Object ref = bridgeDpid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bridgeDpid_ = s;
      return s;
    }
  }
  /**
   * <code>string bridgeDpid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBridgeDpidBytes() {
    Object ref = bridgeDpid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bridgeDpid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORTUUID_FIELD_NUMBER = 2;
  private volatile Object portUuid_;
  /**
   * <code>string portUuid = 2;</code>
   */
  public String getPortUuid() {
    Object ref = portUuid_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      portUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string portUuid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPortUuidBytes() {
    Object ref = portUuid_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      portUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBridgeDpidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bridgeDpid_);
    }
    if (!getPortUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, portUuid_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBridgeDpidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bridgeDpid_);
    }
    if (!getPortUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, portUuid_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PortRequest)) {
      return super.equals(obj);
    }
    PortRequest other = (PortRequest) obj;

    boolean result = true;
    result = result && getBridgeDpid()
        .equals(other.getBridgeDpid());
    result = result && getPortUuid()
        .equals(other.getPortUuid());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BRIDGEDPID_FIELD_NUMBER;
    hash = (53 * hash) + getBridgeDpid().hashCode();
    hash = (37 * hash) + PORTUUID_FIELD_NUMBER;
    hash = (53 * hash) + getPortUuid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PortRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PortRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PortRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PortRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PortRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PortRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PortRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PortRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static PortRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static PortRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PortRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PortRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PortRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *1. rpc deletePort's request message.
   *2. rpc getPortByUuid's request message.
   *3. rpc getInterfaces's request message.
   *4. InterfaceRequest's message item.
   *5. AddInterfaceRequest's message item.
   * </pre>
   *
   * Protobuf type {@code BridgeConfig.PortRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BridgeConfig.PortRequest)
          PortRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BridgeConfigProto.internal_static_BridgeConfig_PortRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BridgeConfigProto.internal_static_BridgeConfig_PortRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PortRequest.class, Builder.class);
    }

    // Construct using PortRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      bridgeDpid_ = "";

      portUuid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BridgeConfigProto.internal_static_BridgeConfig_PortRequest_descriptor;
    }

    public PortRequest getDefaultInstanceForType() {
      return PortRequest.getDefaultInstance();
    }

    public PortRequest build() {
      PortRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public PortRequest buildPartial() {
      PortRequest result = new PortRequest(this);
      result.bridgeDpid_ = bridgeDpid_;
      result.portUuid_ = portUuid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PortRequest) {
        return mergeFrom((PortRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PortRequest other) {
      if (other == PortRequest.getDefaultInstance()) return this;
      if (!other.getBridgeDpid().isEmpty()) {
        bridgeDpid_ = other.bridgeDpid_;
        onChanged();
      }
      if (!other.getPortUuid().isEmpty()) {
        portUuid_ = other.portUuid_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      PortRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (PortRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object bridgeDpid_ = "";
    /**
     * <code>string bridgeDpid = 1;</code>
     */
    public String getBridgeDpid() {
      Object ref = bridgeDpid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bridgeDpid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string bridgeDpid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBridgeDpidBytes() {
      Object ref = bridgeDpid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bridgeDpid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bridgeDpid = 1;</code>
     */
    public Builder setBridgeDpid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bridgeDpid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bridgeDpid = 1;</code>
     */
    public Builder clearBridgeDpid() {
      
      bridgeDpid_ = getDefaultInstance().getBridgeDpid();
      onChanged();
      return this;
    }
    /**
     * <code>string bridgeDpid = 1;</code>
     */
    public Builder setBridgeDpidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bridgeDpid_ = value;
      onChanged();
      return this;
    }

    private Object portUuid_ = "";
    /**
     * <code>string portUuid = 2;</code>
     */
    public String getPortUuid() {
      Object ref = portUuid_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        portUuid_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string portUuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPortUuidBytes() {
      Object ref = portUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        portUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string portUuid = 2;</code>
     */
    public Builder setPortUuid(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      portUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string portUuid = 2;</code>
     */
    public Builder clearPortUuid() {
      
      portUuid_ = getDefaultInstance().getPortUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string portUuid = 2;</code>
     */
    public Builder setPortUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      portUuid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BridgeConfig.PortRequest)
  }

  // @@protoc_insertion_point(class_scope:BridgeConfig.PortRequest)
  private static final PortRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PortRequest();
  }

  public static PortRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PortRequest>
      PARSER = new com.google.protobuf.AbstractParser<PortRequest>() {
    public PortRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PortRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PortRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PortRequest> getParserForType() {
    return PARSER;
  }

  public PortRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

